name: "puppetize"
on:
  schedule:
    - cron: "0 6 1,15 * *"
  workflow_dispatch:
    inputs:
      module_name:
        description: |
          The name of the PowerShell module as it appears on the PowerShell Gallery.
        required: true
        default: "powerstig"
env:
  pdk_version: 2.7.1.0
  module_cache: Puppet.Dsc, PSFramework, PSDscResources, powershell-yaml, PowerSTIG
  powershell_module: powerstig
jobs:
  puppetize:
    runs-on: "windows-latest"
    defaults:
      run:
        shell: powershell
    steps:
      - name: "checkout"
        uses: "actions/checkout@v4"
      - name: "Install required modules"
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          shell: powershell
          modules-to-cache: ${{ env.module_cache }}
      - name: "Install pdk"
        run: |
          choco feature disable -n=showDownloadProgress
          choco install pdk --version ${{ env.pdk_version }} -y
      - name: "Configure WinRM"
        run: |
          Write-Host 'Ensuring WinRM is configured for DSC'
          Get-ChildItem WSMan:\localhost\Listener\ -OutVariable Listeners | Format-List * -Force
          $HTTPListener = $Listeners | Where-Object -FilterScript { $_.Keys.Contains('Transport=HTTP') }
          If ($HTTPListener.Count -eq 0) {
            winrm create winrm/config/Listener?Address=*+Transport=HTTP
            winrm e winrm/config/listener
          }
      - name: "Publish module"
        run: |
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          Import-Module -Name PSDesiredStateConfiguration -Force
          Import-Module -Name Puppet.Dsc -Force
          $null = Get-Command PDK, Publish-NewDscModuleVersion
          $PublishParameters = @{
            ForgeNameSpace = 'nwm'
            Name = '${{ env.powershell_module }}'
            OnlyNewer = $true
            MaxBuildCount = 1
            ForgeToken = '${{ secrets.FORGE_API_TOKEN }}'
          }
          Publish-NewDscModuleVersion @PublishParameters -Verbose
